<%
require 'yaml'
FORMULA = YAML.load_file('terraform/FORMULA')
%>
---
driver:
  name: 'docker'
  volume: '/sys/fs/cgroup:/sys/fs/cgroup:ro'
  cap_add:
    - 'SYS_ADMIN'
  memory: '2G'
  require_chef_omnibus: False
  privileged: true

provisioner:
  name: 'salt_solo'
  salt_bootstrap_url: 'https://github.com/saltstack/salt-bootstrap/releases/latest/download/bootstrap-salt.sh'
  salt_minion_extra_config:
    master: '127.0.0.1'
    color: False
  formula: <%= FORMULA['name'] %>
  <% deps = FORMULA['recommended'].split(',') if (!FORMULA['recommended'].nil? && !FORMULA['recommended'].empty?) %>
  <% if (!deps.nil? && !deps.empty?) %>
  dependencies:
    <% deps.each do |dep| %>
    - path: ../<%= dep.strip() %>-formula
      name: <%= dep.strip() %>
    <% end %>
  <% end %>
  state_top:
    base:
      '*':
        - <%= FORMULA['name'] %>

platforms:
  - name: 'debian-12-slim'
    driver_config:
      provision_command:
        - apt-get install -y --no-install-recommends
          wget curl tar mc apt-utils apt-transport-https locales
        - localedef --no-archive -c -i en_US -f UTF-8 en_US.UTF-8

  - name: 'ubuntu-20.04'
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y --no-install-recommends
          wget curl tar mc apt-utils apt-transport-https locales
        - localedef --no-archive -c -i en_US -f UTF-8 en_US.UTF-8

  - name: 'rockylinux-9-minimal'
    driver_config:
      provision_command:
        - yum install -y -q wget tar mc iproute nmap-ncat passwd glibc-langpack-en

suites:
  - name: <%= FORMULA['name'] %>
